# Generated by Django 4.1.2 on 2022-10-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_employee_details_employee_email_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sdate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
