# Generated by Django 4.1.2 on 2022-10-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_job_user_alter_employee_j'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='j',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.employee'),
        ),
    ]
