# Generated by Django 4.1.2 on 2022-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_employee_j_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
