# Generated by Django 4.1.2 on 2022-10-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_employee_addr_employee_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tempc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tempp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tempt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
